### ISSUE TITLE
Redshift  OCIO

### ISSUE THREAD

**Issue by li-xinshan** [jtomori/batch_textures_convert#2]
We haven't tested it yet, I want to know if it will handle the OCIO problem of Redshift rstexbin?

**Comment by jtomori** [comment]
Hello,
I am not sure what problem you have in mind, but this tool is just running a predefined command on a directory of images.

See the redshift command being used: https://github.com/jtomori/batch_textures_convert/blob/90c6770516fed2b188f21f11031ea124b831f909/scripts/python/batch_convert/converters.py#L112

So if running a `redshiftTextureProcessor` on your textures causes you OCIO problems then this tool will as well.

Best,
Juraj

**Comment by li-xinshan** [comment]
Okay, we started to optimize this process, thank you for your code
